version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./model_files:/app/model_files
      - .:/app
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug --reload
    depends_on:
      - redis

  celery_worker:
    build: .
    volumes:
      - ./model_files:/app/model_files
    env_file:
      - .env
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"